### ISSUE TITLE
return LatLng from picked location

### ISSUE THREAD

**Issue by xyzbilal** [martin-braun/google_maps_place_picker_mb#11] opened 2022-02-25 13:58 UTC
Hi. is there any chance to get coordinates from picked location on map.

**Comment by martin-braun** [comment] 2022-02-25 16:10
Hi, this is a duplicate of #3. Should answer your question. :)

**Closed by martin-braun** 2022-02-25 16:10 UTC
Labels: state:duplicate, type:question

**Comment by xyzbilal** [comment] 2022-02-27 08:16
thanks for info.
