### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by negiot** [martin-braun/google_maps_place_picker_mb#5] opened 2021-11-19 15:12 UTC
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_place_picker_mb-2.0.0-mb.11/lib/src/autocomplete_search.dart:285:69: Error: Too few positional arguments: 2 required, 0 given.
        location: provider.currentPosition == null ? null : Location(lat: provider.currentPosition!.latitude, lng: provider.currentPosition!.longitude),
                                                                    ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_webservice-0.0.19/lib/src/core.dart:7:3: Context: Found this candidate, but the arguments don't match.
  Location(this.lat, this.lng);
  ^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_place_picker_mb-2.0.0-mb.11/lib/src/google_map_place_picker.dart:110:15: Error: Too few positional arguments: 2 required, 0 given.
      Location(lat: provider.cameraPosition!.target.latitude, lng: provider.cameraPosition!.target.longitude),
              ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_webservice-0.0.19/lib/src/core.dart:7:3: Context: Found this candidate, but the arguments don't match.
  Location(this.lat, this.lng);
  ^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_webservice-0.0.19/lib/src/utils.dart:61:27: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    return httpClient.get(url, headers: headers);
                          ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_webservice-0.0.19/lib/src/utils.dart:74:28: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    return httpClient.post(url, body: body, headers: postHeaders);
                           ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/negiot/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/negiot/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TimothyGCY** [comment] 2021-11-23 01:45
I facing the same issue but temporary fixed by replacing `Location(lat: xxx, lng: xxx)` with `Location(lat_value, lng_value)` and wrap `url` with `Uri.parse()`

Note: This is not the best method to issue

**Comment by martin-braun** [comment] 2021-12-07 14:30
@negiot Can you please elaborate for me? Which AVD image are you using? In my tests everything works, even within the Android emulator. Also can you please test the issue with the base repository I forked from, so I know the issue was introduced by me or not?

@TimothyGCY Maybe you can give some more information why this is happening and I can take a deeper look into it. You could also do a PR with your temporary fix and I would improve it, if possible.

My main concern is that I cannot reproduce this issue reported here.

**Comment by TimothyGCY** [comment] 2021-12-07 15:03
> @negiot Can you please elaborate for me? Which AVD image are you using? In my tests everything works, even within the Android emulator. Also can you please test the issue with the base repository I forked from, so I know the issue was introduced by me or not?
> 
> @TimothyGCY Maybe you can give some more information why this is happening and I can take a deeper look into it. You could also do a PR with your temporary fix and I would improve it, if possible.
> 
> My main concern is that I cannot reproduce this issue reported here.

Hi, @martin-braun,
There is actually 2 parts of issues at here:
1. Kind of very straight forward, told from the error itself, variable `url` is not `Uri` but a `String`, so I just used ```Uri.parse(url)``` to solve that.
2. Datatype `Location()` issue, where there is no named parameters (I think that's what you called?)
In the code, `Location(lat: provider.cameraPosition!.target.latitude, lng: provider.cameraPosition!.target.longitude),` which makes user think it is from structure of `Location({double lat, double lng})`. However, what we have is that the structure of `Location` is actually `Location(double lat, double lng)`.

**Comment by martin-braun** [comment] 2021-12-07 15:33
Your `google_maps_webservice` dependency should be `0.0.20-nullsafety.2` not `0.0.19`. The `Location` class as well as the usage of `httpClient` has been changed in `0.0.20-nullsafety.2`: 

<img width="592" alt="Screen Shot 2021-12-07 at 16 16 52" src="https://user-images.githubusercontent.com/24259245/145057963-bd00b3ab-059e-488e-8237-a4b77f5e7daf.png">

<img width="733" alt="Screen Shot 2021-12-07 at 16 30 58" src="https://user-images.githubusercontent.com/24259245/145058332-66c5e4fc-14da-4220-af11-3b7401f2d807.png">

So, this issue is not related to this project, it's an issue that is introduced by a dependency for version mismatch in your own project. So, please make sure your `pubspec.yaml` contains `google_maps_webservice: ^0.0.20-nullsafety.2` and the issue should be gone.

Please report back.

**Comment by nikiman** [comment] 2021-12-07 21:52
> I think the `google_maps_webservice` dependency should be `0.0.20-nullsafety.2` not `0.0.19`. The `Location` class as well as the usage of `httpClient` probably have been changed in `0.0.20-nullsafety.2`. I bet this was a breaking change, although it should not have be. Building works fine for me, although I had the `0.0.19` version in `pubspec.yaml`, but my packages updated and Flutter will not update the `pubspec.yaml`, which is annoying.
> 
> @TimothyGCY Your changes should not be necessary. For instance, see that the Location class in `0.0.20-nullsafety.2` uses named parameters:
> 
> <img alt="Screen Shot 2021-12-07 at 16 16 52" width="592" src="https://user-images.githubusercontent.com/24259245/145063542-d001c6d7-6e0e-481f-a407-5336934d113c.png">
> 
> Can you please try to update `google_maps_webservice` to `0.0.20-nullsafety.2` and see if this fixes the issue?

I confirm that with this configuration there are no more build errors: 

<img width="336" alt="Schermata 2021-12-07 alle 22 48 56" src="https://user-images.githubusercontent.com/2759198/145111760-22e31b92-3f12-49b5-96b0-d20780cee324.png">

**Comment by martin-braun** [comment] 2021-12-08 22:46
Thanks for the feedback. Please update to `2.0.0-mb.13` to fix this issue.

**Closed by martin-braun** 2021-12-08 22:46 UTC
