### ISSUE TITLE
Marker not animating to new position on search

### ISSUE THREAD

**Issue by sarmiladhandapani** [martin-braun/google_maps_place_picker_mb#36] opened 2022-08-05 05:15 UTC
**Describe the bug**
Marker not animating to new position on search

**To Reproduce**
1. Search for any place
2. Click on any place
3. Error comes

**Expected behavior**
When I click on any place name in the search result, the marker should animate to new position

**Screenshots**
**Before Search**
![Screenshot_1659676225](https://user-images.githubusercontent.com/48172133/183006227-5630183e-c3f3-40fe-988e-d21d3e3f73b4.png)

**On Search**
![Screenshot_1659676221](https://user-images.githubusercontent.com/48172133/183006239-46fd93fb-a784-4e1a-9cff-4b46edf8327c.png)

**After Clicking on search result**

![Screenshot_1659676214](https://user-images.githubusercontent.com/48172133/183006259-69a0b6cf-e3f8-4958-a170-1bb364b171d6.png)

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/webnox/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/webnox/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.68.0)
    • VS Code at /Users/webnox/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Device/Emulator/Simulator (and architecture)**
I.e. Pixel 5 API Thiramisu

**Additional context**
**Error Message**

`E/flutter (11982): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_8)
E/flutter (11982): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (11982): <asynchronous suspension>
E/flutter (11982): #1      _PlacePickerState._moveTo (package:google_maps_place_picker_mb/src/place_picker.dart:412:5)
E/flutter (11982): <asynchronous suspension>
E/flutter (11982): #2      _PlacePickerState._pickPrediction (package:google_maps_place_picker_mb/src/place_picker.dart:403:5)
E/flutter (11982): <asynchronous suspension>
E/flutter (11982): 
D/WindowContextController(11982): attachToDisplayArea success, type:2030, displayId:41
D/MapsInitializer(11982): preferredRenderer: null
D/zzca    (11982): preferredRenderer: null
I/Google Maps Android API(11982): Google Play services package version: 220412044
I/Google Maps Android API(11982): Google Play services maps renderer version(legacy): 203115000
D/WindowOnBackDispatcher(11982): App: com.easyfiledservice.app isChangeEnabled=false featureFlagEnabled=true onBackInvokedEnabled=false
D/WindowOnBackDispatcher(11982): App: com.easyfiledservice.app isChangeEnabled=false featureFlagEnabled=true onBackInvokedEnabled=false
V/OnBackInvokedDispatcher(11982): Pending setActual android.view.ViewRootImpl@a5028aa. Current null
V/OnBackInvokedDispatcher(11982): Pending transferring 0 callbacks to android.window.WindowOnBackInvokedDispatcher@e014c9b
D/HostConnection(11982): createUnique: call
D/HostConnection(11982): HostConnection::get() New Host Connection established 0xb400007ceb48f950, tid 14428`

**Comment by martin-braun** [comment] 2022-08-08 09:31
@sarmiladhandapani Some devices seem to report this issue. This is a duplicate #6 and #20 and it seems the issue is caused by the fact that the map will be re-built when your keyboard hides after picking a place from the list.

I close this in favor of continuing the discussion at #20.

**Closed by martin-braun** 2022-08-08 09:31 UTC
