### ISSUE TITLE
After place search, camera#animate doesn't work

### ISSUE THREAD

**Issue by negiot** [martin-braun/google_maps_place_picker_mb#6] opened 2021-11-26 09:51 UTC
E/flutter (30152): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.io/google_maps_2)
E/flutter (30152): #&#8203;0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (30152): <asynchronous suspension>
E/flutter (30152): #&#8203;1      _PlacePickerState._moveTo (package:google_maps_place_picker_mb/src/place_picker.dart:412:5)
E/flutter (30152): <asynchronous suspension>
E/flutter (30152): #&#8203;2      _PlacePickerState._pickPrediction (package:google_maps_place_picker_mb/src/place_picker.dart:403:5)
E/flutter (30152): <asynchronous suspension>

**Comment by martin-braun** [comment] 2021-12-07 14:36
Do you have created and inserted the API key in the keys.dart and AndroidManifest.xml? Could you also try to update the `google_*` packages and see if it helps?

**Comment by berkekesikbas** [comment] 2021-12-20 21:58
> Do you have created and inserted the API key in the keys.dart and AndroidManifest.xml? Could you also try to update the `google_*` packages and see if it helps?

didn't help

**Comment by martin-braun** [comment] 2022-01-08 19:48
@negiot @berkekesikbas I cannot reproduce the issue. `MissingPluginExceptions` are not directly associated to the plugin's code. Try to test on real device. Android or iOS and which device exactly? `flutter doctor` results? Give me as much details as possible, please.

**Comment by martin-braun** [comment] 2022-03-05 20:47
Sorry I need to close this for the lack of details, please reply me if the issue is not fixed by the latest version and I will reopen and try to reproduce again. Please let me know the device you test on and the logs (incl. adb or console).

**Closed by martin-braun** 2022-03-05 20:47 UTC
Labels: state:unclear, type:bug

**Comment by martin-braun** [comment] 2022-08-08 09:36
@negiot, @berkekesikbas I got some further details to investigate. Please follow #20 to get updates on this issue.

**Comment by berkekesikbas** [comment] 2022-08-09 15:08
> @negiot, @berkekesikbas I got some further details to investigate. Please follow #20 to get updates on this issue.

Thank you for information.
