### ISSUE TITLE
App crashed 

### ISSUE THREAD

**Issue by sheikh112233** [martin-braun/google_maps_place_picker_mb#24] opened 2022-05-28 12:57 UTC
**Describe the bug**

**To Reproduce**
1. search location '...'
2. Click on check or tick button '....'

**Expected behavior**
 App should come on previous screen instead of crash
**Screenshots**

**Flutter Doctor -v**

**Additional context**

**Comment by martin-braun** [comment] 2022-05-28 18:35
What is the error? I experience no crashes. Please share the full log. Where is your `flutter doctor -v` output? Also, if logs show nothing, can you please share device logs? On what device are you testing?

**Comment by rehamalraee24** [comment] 2022-06-05 07:17
java.lang.NullPointerException
Attempt to get length of null array
java.nio.ByteBufferAsIntBuffer.put (ByteBufferAsIntBuffer.java:122)
com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i (n.java:2)
com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d (n.java:3)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s (d.java:2)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s (ao.java:12)
com.google.maps.api.android.lib6.gmm6.vector.bz.s (bz.java:29)
com.google.maps.api.android.lib6.gmm6.vector.bs.b (bs.java:151)
com.google.maps.api.android.lib6.gmm6.vector.av.run (av.java:48)

**Comment by martin-braun** [comment] 2022-06-05 11:44
- Please share the output of `flutter doctor -v`.
- Please tell me if this happens anytime or just sometimes.
- Could you please disable minifyEnabled and shrinkResources in your `gradle.build` to see if the crashes continue

Possible Ref: 
- https://stackoverflow.com/questions/27253524/attempt-to-get-length-of-null-array-in-google-maps-v2-android-app
- Maybe a Java workaround: https://github.com/cjmartin2/OneWarmCoat-android/commit/70bdc7a0db1708ab931a81f107b248298a1cfc39

But this is needs to be reported to Flutter and Google Maps directly, because this is a lower level problem within the Google Maps lib and I doubt there is anything I can do, except for redirecting the issue. 

Please answer my questions so I can forward this issue. Thanks.

**Comment by martin-braun** [comment] 2022-07-04 15:52
@TouseefAQ 

> Please share the output of flutter doctor -v.

**Comment by mauriziopinotti** [comment] 2022-07-08 13:51
The same happened to me as well, although it's not 100% reproducible. I think it's a race condition and depends on how fast the connection/device is capable of loading data: on my bench I can reproduce it 30% of the times by immediately confirming the place after geolocation finishes.

**Comment by martin-braun** [comment] 2022-07-10 11:59
@mauriziopinotti Could you please share the output of `flutter doctor -v` and tell me on what emulator/device you are testing, including its API and bit architecture?

**Comment by mauriziopinotti** [comment] 2022-07-11 07:00
> @mauriziopinotti Could you please share the output of `flutter doctor -v` and tell me on what emulator/device you are testing, including its API and bit architecture?

Sure, here's the output of `flutter doctor`:

```
[✓] Flutter (Channel stable, 3.0.4, on Ubuntu 22.04 LTS 5.15.0-40-generic, locale en_US.UTF-8)
    • Flutter version 3.0.4 at /home/maurix/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/maurix/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /home/maurix/Android/Sdk
    • Java binary at: /snap/android-studio/123/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium-browser

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /snap/android-studio/123/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /snap/intellij-idea-ultimate/368
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04 LTS 5.15.0-40-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 103.0.5060.53 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

I reproduced the issue on emulator Pixel 4 API 30 Android 11 x86_64 but also on various real devices (Galaxy S21 and others).

**Comment by martin-braun** [comment] 2022-07-11 09:50
@mauriziopinotti Thank you, I was able to re-produce the issue eventually. The problem was that my build.gradle of my example app was still on "compileSdkVersion 32". Rising it to 33 causes the app to crash. I will find a problem to the fix and get back to you ASAP. I hope others in this thread will look at your post and understand how important it is to share the details that I request to find a solution.

**Comment by martin-braun** [comment] 2022-07-11 12:08
@mauriziopinotti It's hard to band-aid, let me tell you that. As you can read in the linked issue, the problem is a time-issue as you realized. I should've been more patient, it only happens to me in debug mode, when I pick a place immediately without waiting too long. I suspect the Google Maps component still messing with an array that it's navigation-aware logic nulls on pop.

I doubt that I can fix it, but I'm looking for a band-aid that isn't using a duration delay at this point.

**Comment by martin-braun** [comment] 2022-07-11 12:29
@mauriziopinotti Sure thing. Before we decide to report more details on their end (what they have to read and process), I want to clear things up on our end.

> the issue is only reproducible if you do something with the picked result, if you just ignore the PickResult returned by the dialog the crash does not occur.

You said, over there. Seems weird to me, since our `PickResult` is part of this repo and not theirs. I out-commented `selectedPlace = result;` in the callback and still got the crash after 30 tries, you might just had some luck on testing to not catch it, I would remove that comment to prevent any confusion. Simply popping on the callback will cause this issue on rare occasions anyways.

**Comment by martin-braun** [comment] 2022-07-11 13:50
I investigated the wrapper (Flutter and Java part) and I don't see a way to prevent this issue. Further research shows that it's even a thing on ReactNative. Luckily the bug was reported to Google's issue tracker and hopefully it gets addressed ASAP. Unfortunately, any possible band-aid that comes into my mind cannot be applied here, since the exposed API is too limited. The `onMapCreated` callback is fired too early, the `GoogleMap.OnMapLoadedCallback` was never exposed which might call when the initialization is fully complete.

My idea was to lock the pop until it fires, but there is still a slight risk of failure here, since the map view itself will invalidate two frames later.

**Comment by Wian-TMC** [comment] 2022-07-12 07:38
Awesome feedback!!!

**Comment by martin-braun** [comment] 2022-07-12 12:09
Here is a [temporary fix](https://github.com/flutter/flutter/issues/105965#issuecomment-1181637402). Unfortunately, I cannot apply it to my repository, but you can fix the problem by inserting the following to your pubspec.yaml: 

```yaml
dependency_overrides:
  google_maps_flutter:
    git:
      url: https://github.com/lukaskurz/plugins
      path: packages/google_maps_flutter/google_maps_flutter
      ref: main
```

I recommend you to subscribe to this issue here, I will inform you when this has been fixed by the Google team, so that you can remove those lines again. 

Disclaimer: I am not responsible for any damage. You are obliged and required to check the source code of the [repository](https://github.com/lukaskurz/plugins) that is containing the fix. By implementing the above fix, you agree to my disclaimer.

**Comment by giorgio79** [comment] 2022-11-04 19:06
Thx Martin for your efforts. This bug has been killing my app with 3% crash rate. Will try the git repo fix

**Comment by giorgio79** [comment] 2022-11-04 19:11
Martin just tried this fix, but getting a dependency error, so looks like this git fix no longer applies...

`Because google_maps_place_picker_mb 2.0.0-mb.22 depends on google_maps_flutter ^2.1.10 and no versions of google_maps_place_picker_mb match >2.0.0-mb.22 <3.0.0, google_maps_place_picker_mb ^2.0.0-mb.22 requires google_maps_flutter from hosted.`

**Comment by martin-braun** [comment] 2022-12-21 18:09
@giorgio79 I will look into this.

**Comment by martin-braun** [comment] 2022-12-22 05:49
@giorgio79 I updated the dependencies and unfortunately, I was forced to drop Flutter 2 support now, otherwise we wouldn't get access to the renderer initializer API.

Please update your dependencies (incl. this package) and learn how you can trigger the latest renderer from the [example](https://github.com/martin-braun/google_maps_place_picker_mb/blob/57284e559510b00d3f6130c948120d1ed4c16bd4/example/lib/main.dart#L65).

By using the latest renderer, the crashes won't appear anymore. Although some people complain the new renderer to still be very unstable and buggy, Google is probably working heavily on improving such renderer, thus the issue will be gone in the long run. 

Once Google decides the renderer is stable, the renderer will be selected by default.

I consider this issue to be solved. Merry Christmas.

**Closed by martin-braun** 2022-12-22 05:49 UTC
Labels: type:bug, state:onhold

**Comment by canibal1** [comment] 2023-07-18 12:54
@martin-braun  3.0.2  still in version. When the map is opened and then quickly closed, it gives the error here.

**Comment by martin-braun** [comment] 2023-07-18 13:10
@canibal1 Please upgrade to 3.1.1 my friend.

**Comment by canibal1** [comment] 2023-07-18 15:46
@martin-braun  
Thank you for reply,
There is an issue witj upgrading to 3.1.1 because of this dependcy error.


 Because google_maps_webservice 0.0.20-nullsafety.5 depends on http ^0.13.0 and no versions of google_maps_webservice match >0.0.20-nullsafety.5 <0.1.0, google_maps_webservice ^0.0.20-nullsafety.5 requires http ^0.13.0.
And because google_maps_place_picker_mb >=2.0.0-mb.14 depends on google_maps_webservice ^0.0.20-nullsafety.5, google_maps_place_picker_mb >=2.0.0-mb.14 requires http ^0.13.0.
So, because exampleapp  depends on both google_maps_place_picker_mb 3.1.1 and http 1.1.0, version solving failed.

**Comment by canibal1** [comment] 2023-07-18 16:28
@martin-braun
I did as you said and still the app crashes.
<img width="853" alt="Screenshot 2023-07-18 at 19 28 05" src="https://github.com/martin-braun-net/google_maps_place_picker_mb/assets/25279532/181edb36-da9e-4e17-9549-068673ee33e0">

<img width="1229" alt="Screenshot 2023-07-18 at 19 27 14" src="https://github.com/martin-braun-net/google_maps_place_picker_mb/assets/25279532/b2dadb6c-e3d7-4b5c-bf99-81148a4c43af">

**Comment by martin-braun** [comment] 2023-07-18 16:52
This is the same bug that opened this issue originally, and I explained how it can be solved 5(!) comments above your last comment. Please be kind to read: https://github.com/martin-braun-net/google_maps_place_picker_mb/issues/24#issuecomment-1362445762 and https://github.com/flutter/flutter/issues/105965

Your app won't crash when you switch to the latest renderer. If you are still in doubt or have problems, please compile the example project at: https://github.com/martin-braun-net/google_maps_place_picker_mb/tree/master/example

It should not crash and it should show you how to leverage the latest renderer as well as how to switch hybrid composition which can help.
